server:
  port: 8081
spring:
  application:
    name: bud-layui-web
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://bud.com.cn:3301/eureka/