info:
  name: bud
  tel: 157
server:
  port: 3321
#配置文件在本地
#spring.profiles.active=native
##配置文件的目录
#spring.cloud.config.server.native.search-locations: classpath:dev
spring:
  application:
    name: bud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:dev
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://bud.com.cn:3301/eureka/
logging:
  file: "target/bud-config-server.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS




